<?php

namespace ContainerIxi6m9j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JklI5FRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jklI5FR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jklI5FR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ClasseController::delete' => ['privates', '.service_locator.NZmcB1b', 'get_ServiceLocator_NZmcB1bService', true],
            'App\\Controller\\ClasseController::edit' => ['privates', '.service_locator.NZmcB1b', 'get_ServiceLocator_NZmcB1bService', true],
            'App\\Controller\\ClasseController::index' => ['privates', '.service_locator.RblMI1d', 'get_ServiceLocator_RblMI1dService', true],
            'App\\Controller\\ClasseController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ClasseController::show' => ['privates', '.service_locator..HWWlJE', 'get_ServiceLocator__HWWlJEService', true],
            'App\\Controller\\CoursController::delete' => ['privates', '.service_locator.BHmLGFq', 'get_ServiceLocator_BHmLGFqService', true],
            'App\\Controller\\CoursController::edit' => ['privates', '.service_locator.BHmLGFq', 'get_ServiceLocator_BHmLGFqService', true],
            'App\\Controller\\CoursController::index' => ['privates', '.service_locator.7zyAtZq', 'get_ServiceLocator_7zyAtZqService', true],
            'App\\Controller\\CoursController::indexadmin' => ['privates', '.service_locator.7zyAtZq', 'get_ServiceLocator_7zyAtZqService', true],
            'App\\Controller\\CoursController::new' => ['privates', '.service_locator.AD0pPZf', 'get_ServiceLocator_AD0pPZfService', true],
            'App\\Controller\\CoursController::show' => ['privates', '.service_locator.eeiR1bl', 'get_ServiceLocator_EeiR1blService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ClasseController:delete' => ['privates', '.service_locator.NZmcB1b', 'get_ServiceLocator_NZmcB1bService', true],
            'App\\Controller\\ClasseController:edit' => ['privates', '.service_locator.NZmcB1b', 'get_ServiceLocator_NZmcB1bService', true],
            'App\\Controller\\ClasseController:index' => ['privates', '.service_locator.RblMI1d', 'get_ServiceLocator_RblMI1dService', true],
            'App\\Controller\\ClasseController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ClasseController:show' => ['privates', '.service_locator..HWWlJE', 'get_ServiceLocator__HWWlJEService', true],
            'App\\Controller\\CoursController:delete' => ['privates', '.service_locator.BHmLGFq', 'get_ServiceLocator_BHmLGFqService', true],
            'App\\Controller\\CoursController:edit' => ['privates', '.service_locator.BHmLGFq', 'get_ServiceLocator_BHmLGFqService', true],
            'App\\Controller\\CoursController:index' => ['privates', '.service_locator.7zyAtZq', 'get_ServiceLocator_7zyAtZqService', true],
            'App\\Controller\\CoursController:indexadmin' => ['privates', '.service_locator.7zyAtZq', 'get_ServiceLocator_7zyAtZqService', true],
            'App\\Controller\\CoursController:new' => ['privates', '.service_locator.AD0pPZf', 'get_ServiceLocator_AD0pPZfService', true],
            'App\\Controller\\CoursController:show' => ['privates', '.service_locator.eeiR1bl', 'get_ServiceLocator_EeiR1blService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ClasseController::delete' => '?',
            'App\\Controller\\ClasseController::edit' => '?',
            'App\\Controller\\ClasseController::index' => '?',
            'App\\Controller\\ClasseController::new' => '?',
            'App\\Controller\\ClasseController::show' => '?',
            'App\\Controller\\CoursController::delete' => '?',
            'App\\Controller\\CoursController::edit' => '?',
            'App\\Controller\\CoursController::index' => '?',
            'App\\Controller\\CoursController::indexadmin' => '?',
            'App\\Controller\\CoursController::new' => '?',
            'App\\Controller\\CoursController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ClasseController:delete' => '?',
            'App\\Controller\\ClasseController:edit' => '?',
            'App\\Controller\\ClasseController:index' => '?',
            'App\\Controller\\ClasseController:new' => '?',
            'App\\Controller\\ClasseController:show' => '?',
            'App\\Controller\\CoursController:delete' => '?',
            'App\\Controller\\CoursController:edit' => '?',
            'App\\Controller\\CoursController:index' => '?',
            'App\\Controller\\CoursController:indexadmin' => '?',
            'App\\Controller\\CoursController:new' => '?',
            'App\\Controller\\CoursController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
