<?php

namespace ContainerMiFneSu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NZmcB1bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NZmcB1b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NZmcB1b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'classe' => ['privates', '.errored..service_locator.NZmcB1b.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.NZmcB1b": it needs an instance of "App\\Entity\\Classe" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'classe' => 'App\\Entity\\Classe',
            'entityManager' => '?',
        ]);
    }
}
