<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMiFneSu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMiFneSu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMiFneSu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMiFneSu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMiFneSu\App_KernelDevDebugContainer([
    'container.build_hash' => 'MiFneSu',
    'container.build_id' => '578f7d14',
    'container.build_time' => 1704372643,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMiFneSu');
